// <auto-generated />
using System;
using EgebisLeadFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EgebisLeadFinder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918115346_AddApiUsage")]
    partial class AddApiUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EgebisLeadFinder.Models.ApiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("ApiUsages");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("jsonb");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Industry")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RatingJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RatingSignal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("Score");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TitleScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Body = "Sayın {CONTACT_NAME},\n\n{COMPANY_NAME} firmasının {INDUSTRY} alanındaki faaliyetlerini inceledik.\n\nEgebis olarak üretim şirketlerine yönelik SAP danışmanlığı,\nentegrasyon ve özel yazılım çözümleri geliştiriyoruz.\n\nFirmanızın mevcut yapısı ile ilgili kısa bir görüşme yaparak\nkarşılıklı olarak değerlendirebileceğimiz alanlar olup olmadığını\nkonuşmak isteriz.\n\nUygun olduğunuz bir zamanda 20 dakikalık bir görüşme\ngerçekleştirmekten memnuniyet duyarız.\n\nSaygılarımızla,\nEgebis Bilişim",
                            Key = "SAP",
                            Name = "SAP Danışmanlığı",
                            Subject = "Üretim süreçleri ve SAP danışmanlığı hakkında"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Body = "Sayın {CONTACT_NAME},\n\n{COMPANY_NAME} firmasının {INDUSTRY} alanındaki üretim faaliyetlerini inceledik.\n\nEgebis olarak SAP ile mevcut sistemleriniz (üretim hattı, depo,\ne-ticaret, muhasebe) arasındaki entegrasyonları kuruyor,\nveri akışını uçtan uca otomatikleştiriyoruz.\n\nMevcut entegrasyon ihtiyaçlarınızı değerlendirmek üzere\n20 dakikalık kısa bir görüşme yapmak isteriz.\n\nSaygılarımızla,\nEgebis Bilişim",
                            Key = "SAP_ENTEGRASYON",
                            Name = "SAP Entegrasyonu",
                            Subject = "SAP entegrasyonu ve sistem bütünleştirme hakkında"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Body = "Sayın {CONTACT_NAME},\n\n{COMPANY_NAME} firmasının {INDUSTRY} alanındaki çalışmalarını inceledik.\n\nEgebis olarak üretim yapan firmalara özel; iş emri takibi,\nkalite kontrol ve raporlama yazılımları geliştiriyoruz.\n\nSüreçlerinizde yazılımla iyileştirilebilecek alanları\nbirlikte değerlendirmek isteriz.\n\nSaygılarımızla,\nEgebis Bilişim",
                            Key = "URETIM_YAZILIMI",
                            Name = "Üretim Yazılımı",
                            Subject = "Üretim süreçlerinize özel yazılım çözümleri"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Body = "Sayın {CONTACT_NAME},\n\n{COMPANY_NAME} firmasının {INDUSTRY} alanındaki üretim kapasitesini inceledik.\n\nEgebis olarak sahadan gerçek zamanlı veri toplayan MES /\nüretim takip sistemleri kuruyoruz: makine verimliliği (OEE),\nduruş analizi ve anlık üretim raporlaması.\n\nMevcut üretim takip yapınızı konuşmak üzere kısa bir\ngörüşme yapmaktan memnuniyet duyarız.\n\nSaygılarımızla,\nEgebis Bilişim",
                            Key = "MES",
                            Name = "MES / Üretim Takip",
                            Subject = "Üretim takip (MES) sistemleri hakkında"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Body = "Sayın {CONTACT_NAME},\n\n{COMPANY_NAME} firmasının {INDUSTRY} alanındaki faaliyetlerini inceledik.\n\nEgebis olarak kurumsal yazılım, SAP danışmanlığı ve\nsüreç otomasyonu alanlarında çözümler sunuyoruz.\n\nKarşılıklı olarak değerlendirebileceğimiz alanlar olup olmadığını\nkısa bir görüşmede konuşmak isteriz.\n\nSaygılarımızla,\nEgebis Bilişim",
                            Key = "GENEL",
                            Name = "Genel Tanıtım",
                            Subject = "Egebis Bilişim - kurumsal yazılım çözümleri"
                        });
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("SelectedTemplateId");

                    b.HasIndex("Status");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Contact", b =>
                {
                    b.HasOne("EgebisLeadFinder.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Lead", b =>
                {
                    b.HasOne("EgebisLeadFinder.Models.Company", "Company")
                        .WithMany("Leads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgebisLeadFinder.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EgebisLeadFinder.Models.EmailTemplate", "SelectedTemplate")
                        .WithMany()
                        .HasForeignKey("SelectedTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("SelectedTemplate");
                });

            modelBuilder.Entity("EgebisLeadFinder.Models.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
